### ISSUE TITLE
problem with syntax highlighting (in javascript code)

### ISSUE THREAD

**Issue by dietzste** [volkerdobler/gessQ#1]
First off all: Thanks for creating this extension 🥇 ! I'm so glad it exists!

I have noticed a problem that arises with syntax higlighting.
```
// syntax highlighting using \" working fine
text = "some text \"quoted\"";

//  but here ..
$('[name=\"some code here...\"]').val('');
// langauge syntax fails
```

 I created a screenshot to make it more visable:
![image](https://user-images.githubusercontent.com/54585483/147272144-6ac9e77a-7c1e-4805-a745-55c4b126255a.png)

Since the formatting seems to be quite complex, I don't know what the problem is.

**Comment by volkerdobler** [comment]
Thanks for mentioning it - I will have a look into this issue in the next weeks. Currently, I am busy with project work :-)

**Comment by volkerdobler** [comment]
Hallo @dietzste,

I am not sure, if I have a problem understanding the issue correctly, but if you use jQuery to get any DOM element with an attribute "name" and specific value, why do you use the backslashes before the apostrophe?

If I put $('name="some values here"]').val('') syntax highlighting works perfect. The mixture of ' and " works fine for me.

Maybe give a more explicit example so I can follow your idea? Thanks
Volker

**Comment by volkerdobler** [comment]
Hallo @dietzste,

I did another research and I think everything works fine in my syntax highlighting.

As far as I know, the following happened/is true:
1. gessQ. does not allow single quotes as string markers. You have to use double quotes (") - single quotes (') will lead to a syntax error (but I have to check this tomorrow)
2. Therefore, your javascript will be in a double-quoted expression, and will therefore be recognized correctly as a string (the whole javascript is one string. You only need the backslash quote within the javascript, because you use it within javascript="" - correct?

Again, I am happy to change anything - also the double/single quote rule, but currently, I think, it's correct.

Regards,
Volker

**Comment by dietzste** [comment]
Hallo @volkerdobler,

you are absolutely right. A lot of times I'm using ` javascript = " ... ";` as an environment for js-Code.

Your provided syntax-rules would work fine with double quotes, like:
`$('[name="some values..."]').val('');`

But in an ` javascript = " ... ";` - environment I have to use a backslash quote, where syntax highlighting is not working properly:
```
javascript="
    $('[name="some code here..."]').val('');
";
```
as seen here:

![grafik](https://user-images.githubusercontent.com/54585483/151655866-316d8a8d-9acf-48e5-b7de-c327b3b84e9f.png)

I think it might need just a tiny tweak for regognizing `\"` to work perfectly. But I have no clue, where to begin.

**Comment by volkerdobler** [comment]
Maybe I am stupid, but let me try to understand what you need :-)
In the tmLanguage file, the syntax highlighting is defined. It's a very complicated syntax, and to be honest, I don't understand it 100%.
But coming back to your example.

`javascript="` starts (by definition) a string, which ends in your last line `";`.
So EVERYTHING in this string is handled as string (WITHOUT regular gessQ syntax highlighting).
Another example is, that HTML Tags in "label" texts also don't have syntax highlighting - it's just a string for gessQ.

This is the result in my editor:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/6450690/151846604-953eea67-07c1-4d1c-9ca0-b5aaf2be5578.png">

(you can use the command "Developer: Inspect Editor Tokens and Scopes" to see, which scope (base for any syntax highlighting) is at the current curser. In my example, it's a string, not javascript or anything fancy.

If I want/have to change this behaviour, I have to tell the syntax (in the tmLanguage file), a new scope for `javascript="` - and I am not sure, what side effect this will have ...

Did you try the "official supported" notepad++ for your file? Does the notepad++ have any syntax highlighting in javascript-strings?

Talk to you soon,
Volker

**Comment by dietzste** [comment]
I think I found something helpful:

If I open this code in Notepad++ and in vs-code I get two different highlightings:
```
#macro somemacro
	\" another \" doesn't closes the string
	" is needed without \
	\" \" opens string
	" closes String
#endmacro
```
**in vs code:**
![grafik](https://user-images.githubusercontent.com/54585483/152528746-22be941f-3523-4c1c-8629-142a3b7ae03a.png)
**in Notepad++:**
![grafik](https://user-images.githubusercontent.com/54585483/152529367-b37bb3ce-717f-4644-a998-f148b7f42fe0.png)

This means that **syntax highlighting in Notepad++ does not differentiate between `/"` and `"`**
For gessQ it is a dififference, but syntax highlighting in notepad++ ignores it.

I'm sure in vs code the same approach would work: But I think there is even a better solution:

An escaped quote as `/"` should not start a string. Only `"` should start a string. 

```
?!.,;*+#'`=-_^°/\§%&ß () [] {} 
\"... this should not start a string"
"... only this should start a string"
javascript="
    within a string \" works as it
    should
";
```

![grafik](https://user-images.githubusercontent.com/54585483/152528532-38b004ae-9eaf-4bfe-83e7-bb78dfade8e3.png)

This behavoir would lead to a correct syntax highlighting **if it is not between double quotes**.

For code between `javascript=""; ` we need a new scope as you mentioned before.

**Comment by volkerdobler** [comment]
Hi @dietzste,

I think I found it ... I just published version 0.3.2. Please check if it works for you and let me know.
Thanks for your patience.

Volker

**Comment by dietzste** [comment]
Hi @volkerdobler,

i have the updated version, but i see no difference, although the extenstion is updated. 

Regards,
Stefan

**Comment by dietzste** [comment]
Hi @volkerdobler,

it works fine 🏆! Thank you very much 👍  ! 

Stefan
