### ISSUE TITLE
syntax highlighting in entity.other.attribute-name

### ISSUE THREAD

**Issue by dietzste** [volkerdobler/gessQ#2]
Dear @volkerdobler ,

since the update to 0.3.2 there seem to some tiny problems with certain syntax highlighting.

#include and #includeexists are not recognized

```
#include "somefile.q";
#includeifexists "";

#macro somemacro $1
	text = "@insert(somevalue)" some code
#endmacro
#domacro somemacro $1

#define testmode

#ifdef testmode
#else
#endif
```
![image](https://user-images.githubusercontent.com/54585483/152952996-b11c5190-9b32-4f9e-8e8b-3c820f1a5ea9.png)

I checked with version 0.3.1: #include was recognized, but not part as entity other:

![image](https://user-images.githubusercontent.com/54585483/152953314-f700628f-41f1-472b-84b4-74ecb405f3c3.png)

I tried without `#includeifexists` in `<string>(?i:(@insert|#define|#domacro|#ifdef|#ifndef|#include|#macro))\s+[\w_]+</string>` but it does not seem to recognize #include either way.

**Comment by volkerdobler** [comment]
Dear @dietzste,

thanks for the feedback. I had a copy&paste error in the syntax file. Fixed in 0.3.3

Regards,
Volker
